import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getProfileByUserId } from "@/db/queries/profiles-queries";
import { createProfile } from "@/db/queries/profiles-queries";
import { auth } from "@clerk/nextjs/server";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { userId } = await auth()
  
  if (userId) {
    const profile = await getProfileByUserId(userId)
    if (!profile) {
      await createProfile({ userId })
      }
  } 

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={'${geistSans.variable} ${geistMono.variable}'}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}